In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.stats as stats
from numpy import random as rnd

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Data/updated_data.csv')

## Binomial Experiments:

1. Use a binomial experiment to simulate the number of times sales will be recorded in Branch A in Q2 daily. Repeat the simulation for branches B and C, and aggregate the results.
2. Simulate the quantity of products that will be sold in each of the branches in Q2 daily. Note the difference between this and the above objective!

In [3]:
df.head()

Branch Customer_type  Gender            Product_line  Unit_price  Quantity  \
0      A        Member  Female       Health and beauty       74.69         7   
1      C        Normal  Female  Electronic accessories       15.28         5   
2      A        Normal    Male      Home and lifestyle       46.33         7   
3      A        Member    Male       Health and beauty       58.22         8   
4      A        Normal    Male       Sports and travel       86.31         7   

      Total        Date   Time      Payment  Rating  
0  548.9715  2022-01-05  13:08      Ewallet     9.1  
1   80.2200  2022-03-08  10:29         Cash     9.6  
2  340.5255  2022-03-03  13:23  Credit card     7.4  
3  489.0480  2022-01-27  20:33      Ewallet     8.4  
4  634.3785  2022-02-08  10:37      Ewallet     5.3

In [4]:
print(f"Branches that we have: {df['Branch'].nunique()}")
print(f"Product line that we have: {df['Product_line'].nunique()}")

Branches that we have: 3
Product line that we have: 6


In [5]:
# total number of times sales were made in a day
time_sales = np.array([len(df[df['Date'] == i]) for i in df['Date'].unique()])
time_sales

array([12, 11, 14, 14, 12,  9, 16,  9,  9, 10, 13, 16,  8, 20,  8, 13, 11,
       12,  8, 17, 12, 13, 18, 10, 12, 17, 14,  9, 11, 11, 14, 12,  9, 14,
       11, 16, 14,  9,  6, 10, 10, 12, 19, 11,  8, 10, 13,  9,  8,  7, 10,
        8, 11, 17, 17,  8,  8, 13, 13, 10,  6, 10, 11, 12, 16, 10, 18,  7,
        9,  8, 11, 12,  6, 11,  9,  8,  6,  8, 13,  7, 15,  6, 14,  8,  9,
        6, 18, 11,  9])

### Question 1a

#### Branch A

In [6]:
BranchA_df = df.loc[(df.Branch == 'A')]
BranchA_df

Branch Customer_type  Gender            Product_line  Unit_price  \
0        A        Member  Female       Health and beauty       74.69   
2        A        Normal    Male      Home and lifestyle       46.33   
3        A        Member    Male       Health and beauty       58.22   
4        A        Normal    Male       Sports and travel       86.31   
6        A        Member  Female  Electronic accessories       68.84   
..     ...           ...     ...                     ...         ...   
990      A        Normal  Female      Food and beverages       56.56   
992      A        Normal    Male  Electronic accessories       58.03   
997      A        Member    Male      Food and beverages       31.84   
998      A        Normal    Male      Home and lifestyle       65.82   
999      A        Member  Female     Fashion accessories       88.34   

     Quantity     Total        Date   Time      Payment  Rating  
0           7  548.9715  2022-01-05  13:08      Ewallet     9.1  
2           7  340.5255  2022-03-03  13:23  Credit card     7.4  
3           8  489.0480  2022-01-27  20:33      Ewallet     8.4  
4           7  634.3785  2022-02-08  10:37      Ewallet     5.3  
6           6  433.6920  2022-02-25  14:36      Ewallet     5.8  
..        ...       ...         ...    ...          ...     ...  
990         5  296.9400  2022-03-22  19:06  Credit card     4.5  
992         2  121.8630  2022-03-10  20:46      Ewallet     8.8  
997         1   33.4320  2022-02-09  13:22         Cash     7.7  
998         1   69.1110  2022-02-22  15:33         Cash     4.1  
999         7  649.2990  2022-02-18  13:28         Cash     6.6  

[340 rows x 11 columns]

In [7]:
# total number of times sales that were made in branch A daily
BranchA_sales = np.array([len(df[(df['Date'] == j) & (BranchA_df['Branch'] == 'A')]) for j in df['Date'].unique()])
BranchA_sales 

array([5, 4, 5, 6, 3, 4, 6, 2, 3, 3, 2, 6, 3, 5, 2, 5, 5, 5, 5, 2, 3, 7,
       3, 7, 6, 5, 2, 3, 6, 4, 4, 9, 3, 5, 4, 6, 5, 3, 2, 5, 4, 2, 5, 4,
       3, 3, 5, 5, 2, 2, 4, 1, 3, 3, 7, 1, 2, 3, 6, 3, 3, 6, 2, 5, 8, 2,
       4, 3, 4, 1, 3, 5, 2, 4, 1, 3, 4, 2, 2, 2, 6, 1, 3, 6, 2, 2, 4, 5,
       4])

In [8]:
# daily probabilities of success for branch A
Prob_A = [i/j for i, j in zip(BranchA_sales, time_sales)]

# binomial simulation for Branch A
rnd.binomial(time_sales, Prob_A)

array([ 3,  3,  6,  5,  3,  6,  7,  0,  3,  1,  4,  3,  5,  7,  3,  7,  5,
        6,  2,  2,  1,  8,  3,  7,  2,  7,  3,  2,  4,  1,  5, 11,  3,  7,
        5,  5,  8,  3,  2,  4,  6,  1,  7,  5,  6,  2,  5,  2,  1,  2,  3,
        1,  3,  3,  7,  1,  4,  2, 10,  4,  3,  6,  1,  5,  6,  2,  4,  4,
        2,  1,  5,  6,  1,  5,  0,  4,  2,  4,  0,  3,  6,  0,  4,  6,  2,
        0,  4,  5,  2])

In [9]:
# binomial simulation for Branch A with expectation
binomial = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (time_sales, Prob_A)]
np.array(binomial)

array([4, 4, 5, 6, 2, 3, 6, 2, 3, 2, 1, 6, 3, 5, 2, 4, 5, 5, 4, 1, 3, 7,
       2, 6, 5, 4, 1, 3, 6, 4, 4, 9, 3, 5, 3, 5, 5, 3, 2, 4, 4, 2, 5, 3,
       2, 3, 4, 5, 1, 2, 3, 0, 2, 3, 6, 0, 1, 3, 6, 2, 2, 5, 1, 4, 8, 2,
       4, 2, 3, 0, 3, 5, 1, 3, 0, 2, 4, 2, 1, 1, 5, 0, 2, 6, 2, 2, 3, 5,
       3])

In [10]:
# probability of success in Branch A wrt total events
p_BranchA = len(BranchA_df)/len(df)
p_BranchA

0.34

In [11]:
# possible daily outcomes for branch A in Q2
binomial_Q2 = [((sum(rnd.binomial(1000, 0.34, 1000))/1000).astype(int) + rnd.binomial(a, b) - len(BranchA_df)) for a, b in zip (time_sales, Prob_A)]
np.array(binomial_Q2)

array([ 5,  2,  4,  2,  2,  3,  6,  3,  4,  4,  0,  5,  3,  4,  1,  5,  6,
        8,  6,  1,  4,  5,  2,  9,  5,  5,  2,  4,  5,  1,  1,  8,  0,  8,
        6,  5,  7,  1,  1,  6,  4,  3,  4,  4,  1,  3,  4,  4,  0,  2,  3,
        1,  2,  3,  8,  1,  2,  4,  8,  4,  3,  5,  4,  2,  9, -1,  6,  2,
        4,  1,  2,  6,  1,  5,  1,  3,  5,  2,  2,  2,  2, -1,  2,  5,  1,
        2,  2,  6,  3])

#### Branch B

In [12]:
BranchB_df = df.loc[(df.Branch == 'B')]
BranchB_df

Branch Customer_type  Gender            Product_line  Unit_price  \
9        B        Member  Female      Food and beverages       54.84   
10       B        Member  Female     Fashion accessories       14.48   
11       B        Member    Male  Electronic accessories       25.51   
15       B        Member  Female       Sports and travel       93.72   
19       B        Normal  Female      Home and lifestyle       40.30   
..     ...           ...     ...                     ...         ...   
987      B        Member    Male       Health and beauty       62.00   
989      B        Member    Male       Health and beauty       75.37   
991      B        Normal  Female       Sports and travel       76.60   
993      B        Normal    Male     Fashion accessories       17.49   
996      B        Normal  Female      Home and lifestyle       97.38   

     Quantity     Total        Date   Time      Payment  Rating  
9           3   172.746  2022-02-20  13:27  Credit card     5.9  
10          4    60.816  2022-02-06  18:07      Ewallet     4.5  
11          4   107.142  2022-03-09  17:03         Cash     6.8  
15          6   590.436  2022-01-15  16:19         Cash     4.5  
19          2    84.630  2022-03-11  15:30      Ewallet     4.4  
..        ...       ...         ...    ...          ...     ...  
987         8   520.800  2022-01-03  19:08  Credit card     6.2  
989         8   633.108  2022-01-28  15:46  Credit card     8.4  
991        10   804.300  2022-01-24  18:10      Ewallet     6.0  
993        10   183.645  2022-02-22  18:35      Ewallet     6.6  
996        10  1022.490  2022-03-02  17:16      Ewallet     4.4  

[332 rows x 11 columns]

In [13]:
# total number of times sales that were made in branch B daily
BranchB_sales = np.array([len(df[(df['Date'] == j) & (BranchB_df['Branch'] == 'B')]) for j in df['Date'].unique()])
BranchB_sales 

array([ 3,  1,  3,  2,  6,  2,  8,  3,  3,  6,  5,  6,  3,  6,  4,  5,  3,
        3,  1, 10,  8,  2,  9,  3,  3,  7,  6,  3,  1,  4,  4,  1,  3,  6,
        4,  3,  5,  2,  2,  4,  2,  5,  7,  6,  2,  3,  6,  2,  3,  2,  3,
        2,  6, 10,  0,  4,  4,  4,  3,  5,  0,  1,  4,  3,  3,  3,  6,  1,
        2,  4,  5,  3,  3,  3,  2,  3,  1,  3,  5,  2,  6,  2,  7,  0,  6,
        2,  5,  4,  1])

In [14]:
# daily probabilities of success for branch B
Prob_B = [i/j for i, j in zip(BranchB_sales, time_sales)]

# binomial simulation for Branch B
rnd.binomial(time_sales, Prob_B)

array([ 1,  0,  2,  1,  4,  1,  5,  3,  3,  6,  3,  4,  3,  4,  3,  6,  4,
        3,  0, 11,  9,  1, 12,  3,  2,  9,  9,  2,  3,  4,  6,  0,  5,  5,
        4,  3,  3,  1,  3,  4,  2,  8,  7,  7,  3,  4,  6,  2,  3,  2,  3,
        3,  5,  9,  0,  3,  5,  4,  3,  4,  0,  0,  2,  4,  6,  1,  9,  0,
        3,  5,  4,  3,  4,  6,  1,  3,  1,  1,  3,  2,  6,  1,  3,  0,  4,
        2,  3,  3,  2])

In [15]:
# binomial simulation for Branch B with expectation
binomialB = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (time_sales, Prob_B)]
np.array(binomialB)

array([ 3,  0,  2,  2,  5,  2,  7,  2,  3,  6,  5,  6,  2,  5,  4,  4,  2,
        2,  0,  9,  8,  1,  9,  2,  2,  6,  5,  2,  0,  4,  4,  0,  3,  6,
        3,  2,  5,  1,  2,  4,  2,  4,  7,  5,  2,  2,  5,  2,  3,  2,  2,
        1,  5, 10,  0,  4,  4,  3,  3,  5,  0,  0,  4,  3,  3,  2,  5,  1,
        2,  3,  5,  2,  3,  3,  1,  3,  0,  3,  5,  1,  6,  2,  7,  0,  6,
        2,  5,  3,  1])

In [16]:
#probability of success in Branch B wrt total events
p_BranchB = len(BranchB_df)/len(df)
p_BranchB

0.332

In [17]:
#possible daily outcomes for branch B in Q2
binomialB_Q2 = [((sum(rnd.binomial(1000, 0.332, 1000))/1000).astype(int) + rnd.binomial(a, b) - len(BranchB_df)) for a, b in zip (time_sales, Prob_B)]
np.array(binomialB_Q2)

array([ 5, -1,  1,  3,  4,  2,  8,  3,  4,  5,  3,  7,  4,  5,  3,  8,  3,
        4, -1,  6, 10,  1, 10,  4,  1,  9,  7,  3,  1,  4,  4, -1,  0,  1,
        5,  2,  2,  1,  3,  2,  4,  7,  7,  7,  3,  1,  8,  2,  4,  2,  2,
        2,  6,  7,  0,  3,  6,  3,  1,  4,  0,  1,  8,  3,  4,  2,  8,  0,
        1,  3,  5,  5,  2,  2,  2,  4,  0,  4,  4,  3,  5,  0,  6, -1,  2,
        0,  4,  2,  0])

#### Branch C

In [18]:
BranchC_df = df.loc[(df.Branch == 'C')]
BranchC_df

Branch Customer_type  Gender            Product_line  Unit_price  \
1        C        Normal  Female  Electronic accessories       15.28   
5        C        Normal    Male  Electronic accessories       85.39   
7        C        Normal  Female      Home and lifestyle       73.56   
20       C        Member    Male  Electronic accessories       86.04   
34       C        Member  Female      Food and beverages       99.42   
..     ...           ...     ...                     ...         ...   
983      C        Normal    Male       Health and beauty       99.96   
984      C        Normal    Male  Electronic accessories       96.37   
988      C        Member    Male  Electronic accessories       82.34   
994      C        Member  Female  Electronic accessories       60.95   
995      C        Normal    Male       Health and beauty       40.35   

     Quantity     Total        Date   Time  Payment  Rating  
1           5   80.2200  2022-03-08  10:29     Cash     9.6  
5           7  627.6165  2022-03-25  18:30  Ewallet     4.1  
7          10  772.3800  2022-02-24  11:38  Ewallet     8.0  
20          5  451.7100  2022-02-25  11:24  Ewallet     4.8  
34          4  417.5640  2022-02-06  10:42  Ewallet     7.5  
..        ...       ...         ...    ...      ...     ...  
983         7  734.7060  2022-01-23  10:33     Cash     6.1  
984         7  708.3195  2022-01-09  11:40     Cash     6.0  
988        10  864.5700  2022-03-29  19:12  Ewallet     4.3  
994         1   63.9975  2022-02-18  11:40  Ewallet     5.9  
995         1   42.3675  2022-01-29  13:46  Ewallet     6.2  

[328 rows x 11 columns]

In [19]:
# total number of times sales that were made in branch C daily
BranchC_sales = np.array([len(df[(df['Date'] == j) & (BranchC_df['Branch'] == 'C')]) for j in df['Date'].unique()])
BranchC_sales 

array([ 4,  6,  6,  6,  3,  3,  2,  4,  3,  1,  6,  4,  2,  9,  2,  3,  3,
        4,  2,  5,  1,  4,  6,  0,  3,  5,  6,  3,  4,  3,  6,  2,  3,  3,
        3,  7,  4,  4,  2,  1,  4,  5,  7,  1,  3,  4,  2,  2,  3,  3,  3,
        5,  2,  4, 10,  3,  2,  6,  4,  2,  3,  3,  5,  4,  5,  5,  8,  3,
        3,  3,  3,  4,  1,  4,  6,  2,  1,  3,  6,  3,  3,  3,  4,  2,  1,
        2,  9,  2,  4])

In [20]:
# daily probabilities of success for branch C
Prob_C = [i/j for i, j in zip(BranchC_sales, time_sales)]

# binomial simulation for Branch C
rnd.binomial(time_sales, Prob_C)

array([ 5,  7,  7,  4,  3,  2,  3,  6,  1,  0,  7,  8,  1,  6,  0,  3,  3,
        1,  1,  2,  0,  5,  8,  0,  2,  8,  4,  3,  2,  2,  6,  1,  2,  2,
        5,  6,  2,  5,  2,  1,  5,  3, 10,  1,  2,  3,  2,  0,  2,  5,  3,
        5,  4,  7, 12,  2,  4,  9,  5,  2,  5,  4,  8,  4,  5,  5,  8,  2,
        5,  2,  2,  3,  1,  4,  7,  1,  2,  1,  8,  4,  3,  4,  4,  1,  0,
        5, 13,  1,  4])

In [21]:
# binomial simulation for Branch C with expectation
binomialC = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (time_sales, Prob_C)]
np.array(binomialC)

array([4, 6, 5, 6, 2, 2, 1, 3, 2, 0, 6, 3, 1, 9, 2, 2, 2, 4, 1, 4, 0, 4,
       6, 0, 3, 5, 5, 2, 3, 3, 5, 2, 2, 3, 2, 7, 3, 3, 1, 0, 3, 4, 7, 0,
       2, 4, 1, 2, 3, 3, 2, 5, 2, 3, 9, 2, 1, 5, 3, 1, 3, 3, 4, 4, 4, 5,
       7, 3, 3, 3, 2, 3, 1, 3, 6, 2, 1, 3, 6, 3, 2, 3, 4, 2, 0, 2, 9, 2,
       4])

In [22]:
#probability of success in Branch C wrt total events
p_BranchC = len(BranchC_df)/len(df)
p_BranchC

0.328

In [23]:
#possible daily outcomes for branch C in Q2
binomialC_Q2 = [((sum(rnd.binomial(1000, 0.328, 1000))/1000).astype(int) + rnd.binomial(a, b) - len(BranchC_df)) for a, b in zip (time_sales, Prob_C)]
np.array(binomialC_Q2)

array([ 4,  3,  6,  6,  1,  2,  1,  5,  2, -1,  2, -1,  2,  9,  2,  3,  4,
        4,  2,  4, -1,  5,  4, -1,  3,  4,  9,  3,  4,  7,  9,  1,  2,  1,
        3,  7,  3,  2,  2,  0,  1,  4,  9, -1,  5,  2,  2,  4, -1,  3,  2,
        5,  3,  3,  9,  1,  1,  6,  7,  1,  2,  2,  8,  1,  3,  3,  7,  1,
        2,  6,  2,  4,  0,  6,  7,  0,  4,  1,  7,  3,  2,  0,  3,  4,  1,
        0, 12,  2,  4])

#### Aggregating the Results

In [24]:
#generate dates for Q2
Date = []

new_date = pd.date_range(start="2022-04-01", periods=91).to_pydatetime().tolist()

for date in new_date:
    a = str(date)
    Date.append(a.split(' ')[0])
    
agg = pd.DataFrame({'Date': pd.to_datetime(Date[:89]), 
                    'Branch A': binomial_Q2, 
                    'Branch B': binomialB_Q2, 
                    'Branch C': binomialC_Q2})

agg

Date  Branch A  Branch B  Branch C
0  2022-04-01         5         5         4
1  2022-04-02         2        -1         3
2  2022-04-03         4         1         6
3  2022-04-04         2         3         6
4  2022-04-05         2         4         1
..        ...       ...       ...       ...
84 2022-06-24         1         2         1
85 2022-06-25         2         0         0
86 2022-06-26         2         4        12
87 2022-06-27         6         2         2
88 2022-06-28         3         0         4

[89 rows x 4 columns]

### Question 1b

Simulate the quantity of products that will be sold in each of the branches in Q2 daily. Note the difference between this and the above objective!

In [25]:
# total quantity of goods sold daily
Quant_sold = [df.Quantity[df['Date'] == i].sum() for i in df['Date'].unique()]
np.array(Quant_sold)

array([ 55,  60,  95,  87,  70,  42,  66,  59,  55,  53,  73,  99,  43,
       128,  54,  88,  60,  81,  32, 103,  66,  79,  95,  52,  59,  80,
        91,  53,  67,  47,  83,  75,  47,  97,  62,  87,  82,  37,  30,
        45,  56,  60, 106,  63,  37,  57,  84,  52,  54,  34,  50,  58,
        80,  77,  95,  40,  48,  69,  52,  45,  40,  48,  57,  54,  91,
        61,  95,  24,  54,  49,  59,  67,  32,  67,  39,  37,  35,  31,
        64,  27,  80,  18,  82,  40,  37,  40, 117,  50,  61], dtype=int64)

#### Branch A

In [26]:
# total quantity of goods sold in branch A daily 
Quant_soldA = [df.Quantity[(df['Date'] == i) & (BranchA_df['Branch'] == 'A')].sum() for i in df['Date'].unique()]
np.array(Quant_soldA)

array([27, 22, 24, 29, 18, 18, 22, 12, 15, 17, 11, 39, 13, 28, 13, 33, 26,
       37, 24,  5, 21, 39,  9, 34, 26, 21, 15, 22, 34, 26, 29, 57, 17, 38,
       23, 30, 37, 14,  9, 22, 24, 11, 23, 26, 12, 22, 39, 25,  7, 12, 25,
        5, 29,  9, 36,  4,  7, 20, 25, 16, 16, 35,  6, 13, 56, 12, 14, 14,
       23,  7, 21, 24, 15, 23,  3, 19, 25,  5, 15,  9, 37,  3, 13, 31,  3,
       14, 21, 24, 25], dtype=int64)

In [27]:
# daily probabilities of success for branch A
Prob_A = [i/j for i, j in zip(Quant_soldA, Quant_sold)]

# binomial simulation for Branch A
binomial_A = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (Quant_sold, Prob_A)]
np.array(binomial_A)

array([27, 22, 23, 29, 17, 17, 21, 12, 15, 16, 10, 38, 13, 27, 13, 32, 26,
       36, 23,  4, 21, 38,  8, 33, 25, 21, 14, 21, 33, 26, 29, 57, 16, 38,
       22, 30, 37, 13,  9, 21, 23, 10, 22, 26, 11, 21, 39, 24,  6, 11, 24,
        5, 28,  8, 35,  4,  6, 19, 24, 16, 16, 34,  5, 12, 55, 12, 13, 13,
       22,  7, 20, 24, 15, 23,  3, 19, 25,  4, 14,  8, 36,  2, 12, 30,  3,
       14, 21, 24, 24])

In [28]:
# total quantity of goods sold in Branch A for Q1
total_QuantA = BranchA_df['Quantity'].sum()
total_QuantA

1859

In [29]:
# probability of total goods sold in Branch A wrt total goods sold
p_QuantA = total_QuantA/df['Quantity'].sum()
p_QuantA

0.33738656987295823

In [30]:
# possible outcomes of sold goods for branch A in Q2
binomial_AQ2 = [(rnd.binomial(5510, 0.3374, 50000).mean().astype(int) + rnd.binomial(a, b) - total_QuantA) for a, b in zip (Quant_sold, Prob_A)]
np.array(binomial_AQ2)

array([21, 26, 20, 31, 23, 22, 21,  5, 17, 17, 15, 40, 15, 30, 13, 28, 21,
       45, 23,  5, 24, 42,  7, 26, 25, 25, 14, 20, 28, 29, 30, 64, 22, 45,
       34, 40, 37, 20, 10, 26, 15,  8, 34, 34, 12, 28, 36, 22,  8, 15, 22,
        6, 30,  9, 34,  7, 11, 21, 26, 17, 13, 36, 10, 14, 49, 15, 16, 11,
       28,  7, 18, 28, 13, 17,  2, 23, 29,  2, 13,  8, 38,  2, 19, 31,  0,
       12, 28, 24, 26], dtype=int64)

#### Branch B

In [31]:
# total quantity of goods sold in branch B daily 
Quant_soldB = [df.Quantity[(df['Date'] == i) & (BranchB_df['Branch'] == 'B')].sum() for i in df['Date'].unique()]
np.array(Quant_soldB)

array([11,  5, 26, 14, 30,  6, 38, 16, 19, 35, 39, 39, 19, 48, 27, 33, 14,
       24,  1, 59, 37, 14, 52, 18, 11, 28, 45, 17,  4, 12, 31,  9, 15, 43,
       20, 19, 19,  7, 11, 14,  5, 24, 44, 36, 11, 16, 41, 13, 22, 11, 10,
       11, 34, 49,  0, 24, 31, 16, 13, 16,  0,  3, 22, 20, 17, 12, 37,  2,
       14, 24, 28, 20,  8, 19, 12, 15,  4, 15, 18,  6, 22,  7, 38,  0, 25,
       15, 38, 16,  7], dtype=int64)

In [32]:
# daily probabilities of success for branch B
Prob_B = [i/j for i, j in zip(Quant_soldB, Quant_sold)]

# binomial simulation for Branch B
binomial_B = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (Quant_sold, Prob_B)]
np.array(binomial_B)

array([11,  5, 25, 13, 30,  5, 38, 15, 19, 35, 39, 38, 18, 47, 26, 33, 14,
       23,  1, 58, 36, 13, 51, 18, 11, 28, 45, 17,  4, 11, 31,  8, 14, 42,
       19, 18, 19,  7, 11, 14,  4, 23, 44, 35, 11, 16, 40, 12, 22, 11, 10,
       11, 34, 48,  0, 23, 31, 16, 12, 16,  0,  3, 21, 20, 16, 12, 37,  1,
       13, 24, 27, 19,  7, 19, 11, 14,  3, 15, 17,  6, 22,  7, 38,  0, 24,
       14, 37, 16,  7])

In [33]:
# total quantity of goods sold in Branch B for Q1
total_QuantB = BranchB_df['Quantity'].sum()
total_QuantB

1820

In [34]:
# probability of total goods sold in Branch B wrt total goods sold
p_QuantB = total_QuantB/df['Quantity'].sum()
p_QuantB

0.33030852994555354

In [35]:
# possible outcomes of sold goods for branch B in Q2
binomial_BQ2 = [(rnd.binomial(5510, 0.33030853, 100000).mean().astype(int) + rnd.binomial(a, b) - total_QuantB) for a, b in zip (Quant_sold, Prob_B)]
np.array(binomial_BQ2)

array([12,  3, 24, 14, 31,  8, 29, 11, 22, 33, 41, 34, 22, 50, 23, 33,  9,
       26,  1, 60, 39, 15, 58, 16,  9, 20, 48, 13,  2, 15, 24,  8,  9, 37,
       15, 19, 17,  5,  8, 16,  2, 24, 46, 34, 11, 11, 32, 18, 26, 13, 15,
        8, 31, 40, -1, 24, 37, 12, 20, 16,  0,  2, 18, 13, 18,  6, 37,  3,
       13, 21, 24, 22,  9, 23,  9, 14,  2, 20, 12,  8, 19,  5, 34, -1, 29,
       18, 40, 13,  7], dtype=int64)

#### Branch C

In [36]:
# total quantity of goods sold in branch C daily 
Quant_soldC = [df.Quantity[(df['Date'] == i) & (BranchC_df['Branch'] == 'C')].sum() for i in df['Date'].unique()]
np.array(Quant_soldC)

array([17, 33, 45, 44, 22, 18,  6, 31, 21,  1, 23, 21, 11, 52, 14, 22, 20,
       20,  7, 39,  8, 26, 34,  0, 22, 31, 31, 14, 29,  9, 23,  9, 15, 16,
       19, 38, 26, 16, 10,  9, 27, 25, 39,  1, 14, 19,  4, 14, 25, 11, 15,
       42, 17, 19, 59, 12, 10, 33, 14, 13, 24, 10, 29, 21, 18, 37, 44,  8,
       17, 18, 10, 23,  9, 25, 24,  3,  6, 11, 31, 12, 21,  8, 31,  9,  9,
       11, 58, 10, 29], dtype=int64)

In [37]:
# daily probabilities of success for branch C
Prob_C = [i/j for i, j in zip(Quant_soldC, Quant_sold)]

# binomial simulation for Branch C
binomial_C = [(sum(rnd.binomial(a, b, 1000))/1000).astype(int) for a, b in zip (Quant_sold, Prob_C)]
np.array(binomial_C)

array([16, 33, 44, 44, 22, 17,  6, 31, 20,  1, 23, 21, 11, 52, 13, 21, 19,
       20,  6, 39,  8, 25, 34,  0, 22, 31, 30, 14, 28,  9, 23,  8, 14, 15,
       19, 37, 26, 16, 10,  8, 27, 24, 39,  1, 14, 18,  4, 13, 24, 10, 15,
       42, 16, 18, 59, 12, 10, 33, 13, 13, 23, 10, 29, 21, 18, 36, 43,  8,
       17, 18,  9, 23,  9, 24, 24,  2,  6, 10, 30, 11, 21,  8, 30,  9,  8,
       10, 58,  9, 29])

In [38]:
# total quantity of goods sold in Branch C for Q1
total_QuantC = BranchC_df['Quantity'].sum()
total_QuantC

1831

In [39]:
# probability of total goods sold in Branch C wrt total goods sold
p_QuantC = total_QuantC/df['Quantity'].sum()
p_QuantC

0.3323049001814882

In [40]:
# possible outcomes of sold goods for branch C in Q2
binomial_CQ2 = [(rnd.binomial(5510, 0.3323049, 50000).mean().astype(int) + rnd.binomial(a, b) - total_QuantC) for a, b in zip (Quant_sold, Prob_C)]
np.array(binomial_CQ2)

array([13, 32, 49, 48, 24, 16,  6, 31, 17,  1, 30, 20, 15, 57, 12, 20, 14,
       19,  6, 42,  7, 29, 39, -1, 26, 32, 28, 14, 25,  6, 21,  8, 16, 25,
       13, 38, 30, 13, 15,  7, 30, 20, 34,  2, 18, 17,  5, 15, 27, 10, 16,
       41, 11, 17, 47, 15, 13, 31,  9, 13, 21,  8, 28, 16, 11, 33, 49,  6,
       11, 14,  8, 21,  4, 23, 29,  5,  5, 11, 30, 13, 24,  7, 30, 10,  6,
        9, 63, 16, 30], dtype=int64)

#### Aggregating the Results

In [41]:
agg = pd.DataFrame({'Date': pd.to_datetime(Date[:89]), 
                    'Branch A': binomial_AQ2, 
                    'Branch B': binomial_BQ2, 
                    'Branch C': binomial_CQ2})
agg.head()

Date  Branch A  Branch B  Branch C
0 2022-04-01        21        12        13
1 2022-04-02        26         3        32
2 2022-04-03        20        24        49
3 2022-04-04        31        14        48
4 2022-04-05        23        31        24

In [42]:
agg

Date  Branch A  Branch B  Branch C
0  2022-04-01        21        12        13
1  2022-04-02        26         3        32
2  2022-04-03        20        24        49
3  2022-04-04        31        14        48
4  2022-04-05        23        31        24
..        ...       ...       ...       ...
84 2022-06-24         0        29         6
85 2022-06-25        12        18         9
86 2022-06-26        28        40        63
87 2022-06-27        24        13        16
88 2022-06-28        26         7        30

[89 rows x 4 columns]

--------
## Multinomial Simulation & Classification:

* Run a simple multinomial simulation to predict quantity of sales aggregated by branch and classify the branch where the maximum sales would occur daily in Q2. Repeat the steps for predictions based on product line.
* Set up & implement a multinomial Naive Bayes algorithm to predict the branch where each aggregated sale predicted by a binomial simulation will be made daily. Implement the algorithm to classify the product line for each sale batch daily.

### Question 2a

Run a simple multinomial simulation to predict quantity of sales aggregated by branch and classify the branch where the maximum sales would occur daily in Q2. Repeat the steps for predictions based on product line.

In [43]:
# Total quantity of products sold throughout entire sales history
qty_e = df['Quantity'].sum()
qty_e

5510

In [44]:
# Total quantities sold in each branch throughout history: qA, qB, qC

total_QuantA = BranchA_df['Quantity'].sum()
total_QuantB = BranchB_df['Quantity'].sum()
total_QuantC = BranchC_df['Quantity'].sum()

n_ABC = np.array([total_QuantA, total_QuantB, total_QuantC])
n_ABC

array([1859, 1820, 1831], dtype=int64)

In [45]:
# Probability of success for each branch throughout history: pA, pB, pC

p_A = total_QuantA/df['Quantity'].sum()
p_B = total_QuantB/df['Quantity'].sum()
p_C = total_QuantC/df['Quantity'].sum()

p_ABC = np.array([p_A, p_B, p_C])
p_ABC

array([0.33738657, 0.33030853, 0.3323049 ])

In [46]:
# Array of total quantities of products sold each day
Quant_sold = [df.Quantity[df['Date'] == i].sum() for i in df['Date'].unique()]
total_quant = np.array(Quant_sold)
total_quant

array([ 55,  60,  95,  87,  70,  42,  66,  59,  55,  53,  73,  99,  43,
       128,  54,  88,  60,  81,  32, 103,  66,  79,  95,  52,  59,  80,
        91,  53,  67,  47,  83,  75,  47,  97,  62,  87,  82,  37,  30,
        45,  56,  60, 106,  63,  37,  57,  84,  52,  54,  34,  50,  58,
        80,  77,  95,  40,  48,  69,  52,  45,  40,  48,  57,  54,  91,
        61,  95,  24,  54,  49,  59,  67,  32,  67,  39,  37,  35,  31,
        64,  27,  80,  18,  82,  40,  37,  40, 117,  50,  61], dtype=int64)

In [47]:
# Arrays of daily probabilities of success for each branch, A, B, C

# for branch A
Prob_A = [i/j for i, j in zip(Quant_soldA, Quant_sold)]
arrayA = np.array(Prob_A)

# for branch B
Prob_B = [i/j for i, j in zip(Quant_soldB, Quant_sold)]
arrayB = np.array(Prob_B)

# for branch C
Prob_C = [i/j for i, j in zip(Quant_soldC, Quant_sold)]
arrayC = np.array(Prob_C)

In [48]:
# P = PA × PB × PC
res = list(zip(Prob_A, Prob_B, Prob_C))
prob_ABC = np.array(res)

In [49]:
print(f"Shape of total_quant: {total_quant.shape}")
print(f"Shape of p_ABC: {p_ABC.shape}")

Shape of total_quant: (89,)
Shape of p_ABC: (3,)


In [50]:
# # multi_sims = [((sum(rnd.multinomial(5510, p_ABC, 6000))/6000) + rnd.multinomial(a, b).astype(int) - n_ABC) for a, b in zip (total_quant, zip(Prob_A, Prob_B, Prob_C))]
# # multi_sims

# multi_sim = [(rnd.multinomial(5510, p_ABC, 50000).mean(axis=0).round() + rnd.multinomial(a, b).astype(int) - n_ABC) for a, b in zip (total_quant, zip(Prob_A, Prob_B, Prob_C))]
# multi_sim

In [51]:
# for i in multi_sim:
#     print(max(i))

In [52]:
# branch = ['Branch A', 'Branch B', 'Branch C']
# # max_branchindex = []
# # for i in multi_sim:
# #     a = branch[i.argmax(axis=0)]
# #     max_branchindex.append(a)

# max_branchindex = [branch[i.argmax(axis=0)] for i in multi_sim]
# max_branchindex

In [53]:
# Define number of simulations
num_simulations = 5000

# Initialize empty arrays to store results
branch_sales = np.zeros((num_simulations, 3))
product_line_sales = np.zeros((num_simulations, 6))

# Loop through each simulation
for sim in range(num_simulations):
    # Generate random daily sales by branch
    daily_sales = []
    for i in total_quant:
        daily_sales.append(rnd.multinomial(i, p_ABC))

    # Convert to a NumPy array
    daily_sales = np.array(daily_sales)

    # Store daily sales for each branch in the simulation
    branch_sales[sim, :] = daily_sales.sum(axis=0)
    
    # Get unique product lines and corresponding probabilities
    unique_product_lines = df['Product_line'].unique()
    product_line_probs = df.groupby('Product_line')['Quantity'].sum() / df['Quantity'].sum()
    
    # Generate random daily sales by product line
    daily_product_line_sales = []
    for i in total_quant:
        daily_product_line_sales.append(rnd.multinomial(i, product_line_probs))

    # Convert to a NumPy array
    daily_product_line_sales = np.array(daily_product_line_sales)

    # Store daily sales for each product line in the simulation
    product_line_sales[sim, :] = daily_product_line_sales.sum(axis=0)

In [54]:
# Calculate average daily sales by branch
branch_avg_sales = np.mean(branch_sales, axis=0)

# Get the branch with the maximum average daily sales
max_branch = np.argmax(branch_avg_sales)

# Print the results
print("Branch with maximum average daily sales in Q2:", max_branch)

Branch with maximum average daily sales in Q2: 0


In [55]:
# Calculate average daily sales by product line
product_line_avg_sales = np.mean(product_line_sales, axis=0)

# Get the product line with the maximum average daily sales
max_product_line = np.argmax(product_line_avg_sales)

# Print the results
print("Product line with maximum average daily sales in Q2:", max_product_line)

Product line with maximum average daily sales in Q2: 0


In [56]:
# Define number of simulations
num_simulations = 5000

# Initialize empty arrays to store results
branch_sales = np.zeros((num_simulations, 3))
product_line_sales = np.zeros((num_simulations, 6))

# Get the names of the branches and product lines
branch_names = ['Branch A', 'Branch B', 'Branch C']
product_line_names = df['Product_line'].unique()

# Loop through each simulation
for sim in range(num_simulations):
    # Generate random daily sales by branch
    daily_sales = []
    for i in total_quant:
        daily_sales.append(rnd.multinomial(i, p_ABC))

    # Convert to a NumPy array
    daily_sales = np.array(daily_sales)

    # Store daily sales for each branch in the simulation
    branch_sales[sim, :] = daily_sales.sum(axis=0)
    
    # Get unique product lines and corresponding probabilities
    product_line_probs = df.groupby('Product_line')['Quantity'].sum() / df['Quantity'].sum()
    
    # Generate random daily sales by product line
    daily_product_line_sales = []
    for i in total_quant:
        daily_product_line_sales.append(rnd.multinomial(i, product_line_probs))

    # Convert to a NumPy array
    daily_product_line_sales = np.array(daily_product_line_sales)

    # Store daily sales for each product line in the simulation
    product_line_sales[sim, :] = daily_product_line_sales.sum(axis=0)

In [57]:
# Calculate average daily sales for each branch
average_branch_sales = np.mean(branch_sales, axis=0)

# Get the index of the branch with the maximum average daily sales
max_branch_index = np.argmax(average_branch_sales)

# Print the name of the branch with the maximum average daily sales
print("Branch with maximum average daily sales in Q2:", branch_names[max_branch_index])

Branch with maximum average daily sales in Q2: Branch A


In [58]:
# Calculate average daily sales for each product line
average_product_line_sales = np.mean(product_line_sales, axis=0)

# Get the index of the product line with the maximum average daily sales
max_product_line_index = np.argmax(average_product_line_sales)

# Print the name of the product line with the maximum average daily sales
print("Product line with maximum average daily sales in Q2:", product_line_names[max_product_line_index])

Product line with maximum average daily sales in Q2: Health and beauty


### Question 2b
Set up & implement a multinomial Naive Bayes algorithm to predict the branch where each aggregated sale predicted by a binomial simulation will be made daily. Implement the algorithm to classify the product line for each sale batch daily.

In [59]:
df.head()

Branch Customer_type  Gender            Product_line  Unit_price  Quantity  \
0      A        Member  Female       Health and beauty       74.69         7   
1      C        Normal  Female  Electronic accessories       15.28         5   
2      A        Normal    Male      Home and lifestyle       46.33         7   
3      A        Member    Male       Health and beauty       58.22         8   
4      A        Normal    Male       Sports and travel       86.31         7   

      Total        Date   Time      Payment  Rating  
0  548.9715  2022-01-05  13:08      Ewallet     9.1  
1   80.2200  2022-03-08  10:29         Cash     9.6  
2  340.5255  2022-03-03  13:23  Credit card     7.4  
3  489.0480  2022-01-27  20:33      Ewallet     8.4  
4  634.3785  2022-02-08  10:37      Ewallet     5.3

In [60]:
data = df.copy()
data.head()

Branch Customer_type  Gender            Product_line  Unit_price  Quantity  \
0      A        Member  Female       Health and beauty       74.69         7   
1      C        Normal  Female  Electronic accessories       15.28         5   
2      A        Normal    Male      Home and lifestyle       46.33         7   
3      A        Member    Male       Health and beauty       58.22         8   
4      A        Normal    Male       Sports and travel       86.31         7   

      Total        Date   Time      Payment  Rating  
0  548.9715  2022-01-05  13:08      Ewallet     9.1  
1   80.2200  2022-03-08  10:29         Cash     9.6  
2  340.5255  2022-03-03  13:23  Credit card     7.4  
3  489.0480  2022-01-27  20:33      Ewallet     8.4  
4  634.3785  2022-02-08  10:37      Ewallet     5.3

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Branch         1000 non-null   object 
 1   Customer_type  1000 non-null   object 
 2   Gender         1000 non-null   object 
 3   Product_line   1000 non-null   object 
 4   Unit_price     1000 non-null   float64
 5   Quantity       1000 non-null   int64  
 6   Total          1000 non-null   float64
 7   Date           1000 non-null   object 
 8   Time           1000 non-null   object 
 9   Payment        1000 non-null   object 
 10  Rating         1000 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 86.1+ KB


In [62]:
from sklearn.preprocessing import OneHotEncoder

# Convert Date column to datetime
data['Date'] = pd.to_datetime(data['Date'])

In [63]:
# Extract year, month and day information from the Date column
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day

# Drop the original Date column
data.drop(columns=['Date'], inplace=True)

In [64]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le_branch = LabelEncoder()
le_product_line = LabelEncoder()

# Fit and transform the branch and product line columns
data['Branch'] = le_branch.fit_transform(data['Branch'])
data['Product_line'] = le_product_line.fit_transform(data['Product_line'])
data.head()

Branch Customer_type  Gender  Product_line  Unit_price  Quantity     Total  \
0       0        Member  Female             3       74.69         7  548.9715   
1       2        Normal  Female             0       15.28         5   80.2200   
2       0        Normal    Male             4       46.33         7  340.5255   
3       0        Member    Male             3       58.22         8  489.0480   
4       0        Normal    Male             5       86.31         7  634.3785   

    Time      Payment  Rating  Year  Month  Day  
0  13:08      Ewallet     9.1  2022      1    5  
1  10:29         Cash     9.6  2022      3    8  
2  13:23  Credit card     7.4  2022      3    3  
3  20:33      Ewallet     8.4  2022      1   27  
4  10:37      Ewallet     5.3  2022      2    8

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [66]:
# Extract independent variables
X = data[['Quantity', 'Year', 'Month', 'Day']]

# Extract target variables
y_branch = data['Branch']
y_product_line = data['Product_line']

# Split the data into train and test sets
X_branch_train, X_branch_test, y_branch_train, y_branch_test = train_test_split(X, y_branch, test_size=0.3, random_state=42)
X_product_line_train, X_product_line_test, y_product_line_train, y_product_line_test = train_test_split(X, y_product_line, test_size=0.3, random_state=42)

In [67]:
# Fit the Multinomial Naive Bayes model on the training data
mnb_branch = MultinomialNB()
mnb_branch.fit(X_branch_train, y_branch_train)

mnb_product_line = MultinomialNB()
mnb_product_line.fit(X_product_line_train, y_product_line_train)

MultinomialNB()

In [69]:
# Predict the branch and product line for each sale batch
y_branch_pred = mnb_branch.predict(X_branch_test)
y_product_line_pred = mnb_product_line.predict(X_branch_test)

# Evaluate the performance of the model
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy score for branch prediction:", accuracy_score(y_branch_test, y_branch_pred))
print("Classification report for branch prediction:\n", classification_report(y_branch_test, y_branch_pred))

Accuracy score for branch prediction: 0.30666666666666664
Classification report for branch prediction:
               precision    recall  f1-score   support

           0       0.32      0.25      0.28       102
           1       0.28      0.38      0.32        92
           2       0.33      0.30      0.32       106

    accuracy                           0.31       300
   macro avg       0.31      0.31      0.31       300
weighted avg       0.31      0.31      0.30       300



In [70]:
print("Accuracy score for product line prediction:", accuracy_score(y_product_line_test, y_product_line_pred))
print("Classification report for product line prediction:\n", classification_report(y_product_line_test, y_product_line_pred))

Accuracy score for product line prediction: 0.16666666666666666
Classification report for product line prediction:
               precision    recall  f1-score   support

           0       0.24      0.20      0.22        56
           1       0.15      0.32      0.21        53
           2       0.13      0.07      0.09        44
           3       0.00      0.00      0.00        49
           4       0.16      0.40      0.23        47
           5       0.00      0.00      0.00        51

    accuracy                           0.17       300
   macro avg       0.11      0.16      0.12       300
weighted avg       0.12      0.17      0.13       300



## Poisson Processes: 

Use the Poisson process to predict the quantity of products that will be sold each day across each of the branches in Q2. Run a different simulation to estimate the waiting times between each sale, from day to day.

##  Robust Bayesian Inference:
Combine the results from the multinomial and Poisson processes in the Q2
simulation for all 3 branches, and use Bayesian inference to predict the product line for each sale that will be made in Q2 given the branches.